# Generated by Django 4.2.5 on 2023-10-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_inkling_created_at_inkling_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inkling',
            old_name='text',
            new_name='content',
        ),
        migrations.AddField(
            model_name='inkling',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
