# Generated by Django 4.2.5 on 2023-10-04 16:04

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_inkling_title_inkling_embedding_tag_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='embedding',
            field=pgvector.django.VectorField(dimensions=768, null=True),
        ),
    ]
