# Generated by Django 4.2.5 on 2023-10-05 14:25

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_memo_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='content',
            field=martor.models.MartorField(),
        ),
    ]
