# Generated by Django 4.2.5 on 2023-10-05 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_memo_content'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='link',
            unique_together={('source_inkling', 'target_inkling', 'link_type')},
        ),
    ]
