# Generated by Django 4.2.5 on 2023-10-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_link_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='linktype',
            name='reverse_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
