# Generated by Django 4.2.5 on 2023-10-08 19:53

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_link_user_linktype_created_at_linktype_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inkling',
            name='content',
            field=martor.models.MartorField(),
        ),
    ]
