# Generated by Django 4.2.5 on 2023-10-10 03:35

from django.db import migrations, models
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_inkling_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='embedding',
            field=pgvector.django.VectorField(dimensions=768, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='tags',
            field=models.ManyToManyField(blank=True, to='app.tag'),
        ),
    ]
