# Generated by Django 4.2.5 on 2023-10-10 15:49

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_link_embedding_link_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inkling',
            name='embedding',
            field=pgvector.django.VectorField(dimensions=384, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='embedding',
            field=pgvector.django.VectorField(dimensions=384, null=True),
        ),
        migrations.AlterField(
            model_name='memo',
            name='embedding',
            field=pgvector.django.VectorField(dimensions=384, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='embedding',
            field=pgvector.django.VectorField(dimensions=384, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='embedding',
            field=pgvector.django.VectorField(dimensions=384, null=True),
        ),
    ]
