# Generated by Django 4.2.5 on 2023-10-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_inkling_embedding_alter_link_embedding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='summary',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reference',
            name='summary',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
