# Generated by Django 4.2.5 on 2023-10-11 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0016_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='inkling',
            name='privacy_setting',
            field=models.CharField(choices=[('private', 'Private'), ('friends', 'Friends'), ('friends_of_friends', 'Friends of Friends')], default='private', max_length=20),
        ),
        migrations.AddField(
            model_name='memo',
            name='privacy_setting',
            field=models.CharField(choices=[('private', 'Private'), ('friends', 'Friends'), ('friends_of_friends', 'Friends of Friends')], default='private', max_length=20),
        ),
        migrations.AddField(
            model_name='reference',
            name='privacy_setting',
            field=models.CharField(choices=[('private', 'Private'), ('friends', 'Friends'), ('friends_of_friends', 'Friends of Friends')], default='private', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='app.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_requests', to='app.userprofile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='app.userprofile')),
            ],
            options={
                'unique_together': {('sender', 'receiver')},
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='received_friend_requests',
            field=models.ManyToManyField(blank=True, related_name='received_requests', through='app.FriendRequest', to='app.userprofile'),
        ),
    ]
